package com.backoffice.enums;

public enum Accion {
	NINGUNA, 
	ALTA_ESTABLECIMIENTO, 
	NUEVA_OFERTA, 
	RESERVA, 
	APROBAR_SOLICITUD, 
	DESAPROBAR_SOLICITUD, 
	ALTA_SERVICIO,
	ALTA_AGENCIA,
	ALTA_PAQUETE,
	BUSQUEDA_PAQUETE,
	BUSQUEDA_HOTEL,
	ALTA_TIPO_SERVICIO,
	LIMPIEZA_LOGS,
	LIMPIEZA_SOLICITUDES
}
